### ISSUE TITLE
maven repository update

### ISSUE THREAD

**Issue by Adam5Wu** [npgall/mobility-rpc#10]
Fantastic work! Could you please update the maven repository with the latest release? I could only find version 1.1.0, which seems to be quite out-dated.

**Comment by npgall** [comment]
I have just released version 1.2.0.
It's now in Sonatype's public repository https://oss.sonatype.org/index.html#view-repositories;releases~browsestorage~/com/googlecode/mobilityrpc/mobility-rpc/1.2.0

From Sonatype's repository, it should sync to Maven Central in ~2 hours.

However Sonatype's Nexus server gave a 500 error during the releasing process, which has never happened before. So I hope it was a bug in their UI and not in their underlying syncing process, and that it will sync as normal to Maven Central soon. Let me know if you have any problems access it.

**Comment by npgall** [comment]
Version 2.5.0 did sync as normal to Maven Central. Closing this issue.
